data = "Massachusetts Institute of Technology (MA / USA). Senior Lecturer in Spanish (5 years). Spanish. September 1, 2022. website: https://academicjobsonline.org/ajo/jobs/21836
University of California, Santa Barbara. Lecturer, Spanish and Portuguese. June 23, 2022. https://recruit.ap.ucsb.edu/JPF02148
University of Minnesota (MN/USA). Visiting Assistant Professor. (Early Modern and/or Contemporary Iberia). June 20, 2022. https://hr.myu.umn.edu/jobs/ext/348437
Loyola University Maryland (MD/USA). Visiting Assistant Professor of Spanish. May 23, 2022, open until filled. https://careers.loyola.edu/postings/6125
University of Indianapolis (IN / USA). TT Assistant Professor of Spanish. Spanish. https://uindy.hyrell.com/UI/Views/Applicant/VirtualStepPositionDetails.aspx?enc=wNcSyB2j8jVQfA2cJTWegDeKGFvynWyO-JrdR7KPuI0=&tzi=Eastern%20Standard%20Time
Massachusetts Institute of Technology (MA / USA). Lecturer in Spanish (one year). Spanish. March 31, 2022. https://academicjobsonline.org/ajo/jobs/21285
Cal Poly Humboldt (Formerly Humboldt State University | Arcata, CA) TT Assistant Professor of Bilingual Studies. First application review date: February 15, 2022. https://apply.interfolio.com/100747
University of Arkansas (Fayetteville, AR) - TT Assistant Professor of Spanish (Applied Spanish Linguistics/SLA). Deadline: February 6th, 2022 - Open Until Filled. https://uasys.wd5.myworkdayjobs.com/en-US/UASYS/job/Fayetteville/Assistant-Professor-of-Spanish_R0008055?source=HigherEdJobs
Indiana University, Bloomington (Bloomington, IN) - TT Assistant Professor of Spanish Linguistics (Spanish Heritage Language & Linguistics). Deadline: January 10th, 2022 - Open Unitl Filled. https://indiana.peopleadmin.com/postings/12137
Colorado Mesa University (Grand Junction, CO) - **2 POSITIONS** (TT? Dice Full-Time) Assistant Professors of Spanish (One in translation/interpretation) Deadline: Priority Januart 21, 2022, Open Until Filled. https://coloradomesa.csod.com/ux/ats/careersite/1/home/requisition/574?c=coloradomesa
Maryville College (Maryville, TN) - TT Assistant Professor of Spanish (Linguistics, Applied Linguistics, or SLA) Deadline: January 14th, 2022. https://www.paycomonline.net/v4/ats/web.php/jobs/ViewJobDetails?job=49925&clientkey=1064DAE0FBE4FE97CBC8BAA9499D8EE7
New Mexico Highlands University (Las Vegas, NM) - TT Assistant/Associate Professor of Spanish Linguistics. Deadline: Open Until Filled, Closing Date: February 1st, 2022. https://nmhu.peopleadmin.com/postings/7123
Syracuse University (Syracuse, NY) - TT Assistant Professor of Latinx Literature and Culture. Deadline: Priority January 5th, 2022, Open Until Filled. https://www.sujobopps.com/postings/90013
Queens College CUNY (New York, NY) - TT Assistant Professor of Hispanic Linguistics. Deadline: Open Until Filled, Review of Applications starts December 12. https://cuny.jobs/queens-ny/assistant-professor-hispanic-languages-and-literatures/473AA2A0DACA4588B9BD2CEBD86B2405/job/
  UC San Diego (San Diego, CA) - Associate Teaching Professor of Spanish as a Second Language and Spanish for Heritage Speakers. Deadline: Dec 15th. https://apol-recruit.ucsd.edu/JPF02978?fbclid=IwAR1PuS5O5ui0c5nB0HY9x3RRWhf05SlqtieeQlGcqOWgnKpBy4ago6Izy60
Central Connecticut State University (New Britain, CT) - TT Assistant Professor of Spanish (Contemporary Latin American literature and culture - Priority for expertise in Central and South America, including indigenous literature and culture of the Andes). Deadline: December 27th. https://host.pcrecruiter.net/pcrbin/jobboard.aspx?JOBSHARERWMYH4Y3WW6XZZVKG2Y2W4PVV3FOWQMU4GG62TFLP7M4NVONSXIM7ZMPYM2U5PTDKURYUFUXKD6ZSTFDPSEM3A62CIFEZNHF2HOERNHMLZH2X2WCJCGAFLSD5NG6QQD3EN2KUGM6LDAFFTZTIH634DPIZS64TK4THULA
University of Oxford (Oxford, UK) - Departmental Lecturer in Spanish and Portuguese Deadline: Dec 3rd. https://www.jobs.ac.uk/job/CKU720/departmental-lecturer-in-spanish-and-portuguese-linguistics
Mount St. Mary's University (Maryland) - Non TT - Assistant Professor of Latin American Literature and Spanish Language. Deadline: Open until filled. https://joblist.mla.org/job-details/5147/assistant-professor-of-latin-american-literature-and-spanish-language/?porder=Spanish#top-pagination
Queens University of Charlotte (Charlotte, NC) - TT (Open-rank) Professor of Spanish (Latin America). Deadline: January 15, 2022. https://www.higheredjobs.com/faculty/details.cfm?JobCode=177683770&Title=Spanish%20Faculty%20%28Open%20Rank%20Tenure%2DTrack%20Position%29
University of Central Missouri (Warrensburg) - TT Assistant Professor of Spanish (Generalist). Deadline: Open until filled (review will begin immediately). https://jobs.ucmo.edu/postings/26247
Nebraska Wesleyan University (Lincoln, NE) - TT Assistant Professor of Spanish (Generalist/SLA). Deadline: Open until filled (Review of applications will begin immediately). https://nebrwesleyan.applicantpro.com/jobs/2078616.html
University of Arizona (Tucson, AZ) - TT Assistant Professor of Hispanic Linguistics (SLA of Spanish morphosyntax). Deadline: December 1. https://arizona.csod.com/ux/ats/careersite/4/home/requisition/7031?c=arizona
LeMoyne College (Syracuse, NY) - TT Assistant Professor of Spanish (Latin American and/or Caribbean Literature and Culture). Deadline: December 1. https://lemoyne.interviewexchange.com/jobofferdetails.jsp?JOBID=138269
University of Mississippi (Oxford, MS) - TT Assistant Professor of Spanish Linguistics (Computational and/or Corpus Linguistics). Deadline: None given. https://careers.olemiss.edu/job/University-Assistant-Professor-of-Spanish-Linguistics-MS-38677/800509400/
Truman State University (Kirksville, MO) - TT Assistant Professor of Spanish (Hispanic Linguistics). Deadline: December 3. https://secure.truman.edu/positionlisting-s/positiondetails.asp?positionId=4975
Mississippi State University (Starkville, MS) - Assistant Professor of Spanish Linguistics (TT). Deadline: Open Until Filled. https://explore.msujobs.msstate.edu/en-us/job/503338/assistant-professor
University of Houston - Associate Professor Creative Writing in Spanish. Deadline, Nov. 15 https://joblist.mla.org/employer-details/1865/university-of-houston-central_hispanic-studies-department/
Bucknell University (Lewisburg, PA). Visiting Assistant Professor of Spanish. Latin American Cultures/Literatures. https://joblist.mla.org/job-details/5087/visiting-assistant-professor-of-spanish/?porder=Spanish&ix=5#top-pagination
University of North Florida (Jacksonville, FL, USA). Assistant Professor of Spanish/ Latin American Studies (TT), open specialization. Full consideration: November 30, 2021. https://www.higheredjobs.com/details.cfm?JobCode=177667939
Jacksonville University (Jacksonville, FL, USA). not a duplicate with above. do not delete. Assistant Professor of Spanish Language and culture (TT), open specialization. Full consideration: November 12, 2021. https://joblist.mla.org/job-details/4929/assistant-professor-of-spanish-language-and-culture/?porder=Spanish%7cFlorida&ix=4#top-pagination
High Point University (North Carolina, USA). Assistant Professor of Spanish (Non-TT). Latin American Literature and Culture. Deadline: November 10, 2021. https://highpoint.wd1.myworkdayjobs.com/en-US/Highpoint-Faculty/job/High-Point-University/Assistant-Professor-of-Spanish--Non-tenure-track-_R0003896
Oklahoma State University (Oklahoma, USA): Assistant Professor of Spanish with a specialization in Colonial Latin American literature (Tenure Track). Deadline: November 28, 2021. https://joblist.mla.org/job-details/4956/assistant-professor-of-spanish/?porder=Spanish&ix=5#top-pagination
University of Oxford (Oxford, United Kingdom). Departmental Lecturer in Spanish (2 posts, non-tenure, Jan-Sep 2022). Specialisation in Early Modern / Golden Age / Colonial. Deadline: October 25th, 2021 https://my.corehr.com/pls/uoxrecruit/erq_jobspec_details_form.jobspec?p_id=153682 NB: The short deadline on this is to ensure that two maternity covers are filled before due dates.
Ashland University (Ashland, OH). Assistant Professor of Spanish (non-tenure) https://jobs.ashland.edu/postings/1246
Boston University (Boston, MA). Associate or Full Professor of Spanish (tenured) with specialization in modern and contemporary Spanish literature and its transatlantic dimensions. Deadline: October 21st. https://academicjobsonline.org/ajo/jobs/19497
University of Nevada, Las Vegas: Non-TT Assistant Professor-in-Residence in Spanish. Focus on Spanish for the Professions Courses. Deadline: November 1. https://joblist.mla.org/job-details/4615/assistant-professor-in-residence-spanish/?porder=Professor%2c+Assistant%7cSpanish&ix=5#top-pagination
University of Nevada, Las Vegas: TT Assistant Professor of Spanish Translation. Deadline: November 1. https://joblist.mla.org/job-details/4546/assistant-professor-spanish-translation/?porder=Professor%2c+Assistant%7cSpanish&ix=13#top-pagination
Berea College (Berea, KY): TT Assistant Professor of Spanish, Latin American Literature and Culture. Deadline: November 4, 2021. https://myberea.csod.com/ats/careersite/jobdetails.aspx?site=3&c=myberea&id=955
Wesleyan University (Middletown, CT): TT Assistant Professor of Spanish, Modern Latin American literature and culture. Deadline: December 1, 2021. https://careers.wesleyan.edu/postings/8130
Carleton College (Northfield, MN): TT Assistant Professor of Spanish, Latin American literature and culture. Deadline: October 15, 2021. https://careers.carleton.edu/en-us/job/492333/assistant-professor-of-spanish
Southern Utah University (Cedar City, UT): TT Assistant Professor of Spanish, Contemporary Southern Cone literature. Deadline: September 17, 2021. https://suu.applicantpro.com/jobs/1904347.html
University of Rochester (Rochester, NY): TT Assistant Professor of Spanish, Hispanophone Caribbean Literature and Culture. Deadline: October 15, 2021. https://www.rochester.edu/faculty-recruiting/positions/show/11952
Trinity College Dublin, The University of Dublin (Dublin, Ireland): TT Assistant Professor in Twentieth and Twenty-First-Century Spanish Peninsular Studies.Deadline: July 21, 2021. https://my.corehr.com/pls/trrecruit/erq_jobspec_version_4.display_form
Claremont McKenna College (Claremont, CA). Assistant Professor of Spanish. Deadline: November 1st, 2021. https://webapps.cmc.edu/jobs/faculty/faculty_opening_detail.php?PostingID=16071
Baylor University: Modern Languages and Cultures (Waco, TX): Assistant Professor , TT Spanish, Hispanic Linguistics. Deadline: October 31st, 2021. https://apply.interfolio.com/89575
Kenyon College (Gambier, OH). Assistant Professor of Spanish (lit cult Mexico and Central America). Deadline: Oct 10th. https://careers.kenyon.edu/en-us/job/492767/assistant-professor-of-spanish
Cornell University (Ithaca, NY). Assistant Professor or Associate Professor of Hispanic Studies (20th/early 21st century Latin American literature and culture). Deadline: Oct 31st. https://academicjobsonline.org/ajo/jobs/19359
Chapman University (Orange, CA). Assistant Professor of Spanish Literature. Deadline: November 1st. https://web.chapman.edu/jobs/job.aspx?id=1225
The University of New Orleans (New Orleans, LA). Assistant Professor of Spanish (20th and 21st Century Latin American literature and contemporary Spanish Peninsular literature). Deadline: Until post is filled. https://ulsuno.wd1.myworkdayjobs.com/en-US/UniversityOfNewOrleans/job/New-Orleans-La/Assistant-Professor-of-Spanish_R-000289
University of Puget Sound (Tacoma, WA). Assistant Professor of Spanish with a specialization in Mexico, Central America and/or the U.S. Deadline: October 11th. https://www2.pugetsound.jobs/psc/HR92PRD/EMPLOYEE/HRMS/c/HRS_HRAM_FL.HRS_CG_SEARCH_FL.GBL?Page=HRS_APP_JBPST_FL&Action=U&FOCUS=Applicant&SiteId=3&JobOpeningId=6108&PostingSeq=1
Rutgers University (New Brunswick, NJ). Assistant Professor of Spanish Linguistics (Sociolinguistics) Deadline: November 11th https://jobs.rutgers.edu/postings/141655
University of California, Irvine (Irvine, CA). Assistant Professor of Comparative Literature and of History (specialization in Mexico and/or Central America). Deadline: November 1. https://recruit.ap.uci.edu/JPF07021
California State University, Fullerton (Fullerton, CA). Assistant Professor of Spanish Peninsular Contemporary Literary and Cultural Studies (Modern Peninsular Lit) Deadline: November 8. https://careers.pageuppeople.com/873/fl/en-us/job/505522/assistant-professor-of-spanish-peninsular-contemporary-literary-and-cultural-studies
John Jay College of Criminal Justice (New York City, NY). Assistant Professor of Spanish—Specialist in Translation and Interpreting Deadline: December 1st https://cuny.jobs/new-york-ny/assistant-professor-of-spanishspecialist-in-translation-and-interpreting/80B09FD020224D0F95C1D8559B43EE65/job/
San José State University (San José, CA). Assistant Professor of Spanish Translation & Interpretation. Deadline: October 30th https://jobs.sjsu.edu/en-us/job/504938/assistant-professor-of-spanish-translation-and-interpretation?lApplicationSubSourceID=11261
University of St Andrews (Scotland). Lecturer (Assistant Professor) in Latin American Studies. Deadline: December 21st. https://www.vacancies.st-andrews.ac.uk/ViewVacancyV2.aspx?enc=mEgrBL4XQK0+ld8aNkwYmEeQwp6u1UPLJbcPQhhYA7Gtepm3vUz9H8aH4tvQjnuQoqGtbennXxnmjPGU+7706gjMPtDnsfzcmlJKa5ouUwEmsxwIPTO3H/kzPK6QJTR0
Wartburg College (Waverly, IA). Assistant Professor of Spanish (open specialization). Deadline: until position is filled. https://joblist.mla.org/job-details/5477/assistant-professor-of-spanish/?porder=Spanish&ix=5#top-pagination
University of Edinburgh (UK). Lecturer/Senior Lecturer (Assistant/Associate Professor) in Lusophone Studies. Deadline: May 4th (be with you ;-)). https://elxw.fa.em3.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/3664?fbclid=IwAR1PndXEdmqfR1eQ1xt1hcnKlHrCETmE1iR09KyI0uz6ENGhpNTJglqd3TQ
Taylor University, Upland (Indiana). Visiting Professor. 1-2 years. Renewable contract. https://jobs.chronicle.com/job/474880/announcement-of-faculty-opening-in-spanish-department-of-english-and-modern-languages/"
