data = "Rutgers University (New Brunswick, New Jersey, USA). Spanish Language Program Coordinator (non-tenure track, 1 year with possibility of renewal). Deadline: Apply by June 30th. https://www.higheredjobs.com/faculty/details.cfm?JobCode=178431224&Title=Spanish%20Language%20Program%20Coordinator
University of California, Santa Barbara (California, USA). Lecturer in Spanish (non-tenure track, 1 year with possibility of renewal). Spanish. Deadline: Apply by this June 6,2023 to ensure full consideration by the committee. https://recruit.ap.ucsb.edu/JPF02481
University of Puget Sound (Tacoma, WA, USA). Visiting Assistant Professor of Spanish (non-tenure track, 1 year). Spanish. Deadline: open until filled. https://www2.pugetsound.jobs/psc/HR92PRD/EMPLOYEE/HRMS/c/HRS_HRAM_FL.HRS_CG_SEARCH_FL.GBL?Page=HRS_APP_JBPST_FL&Action=U&FOCUS=Applicant&SiteId=3&JobOpeningId=7004&PostingSeq=1&fbclid=IwAR107vl8lSQgENgKlzLwLi9uzRjGk64VMGoTkHg7wtZCMQp4m3IYX_ThuAE&
University of Alabama (Tuscaloosa, AL, USA). Assistant Professor of Spanish (Non-tenure track renewable contract NTRC). Spanish Language Program Director (elementary and intermediate). Deadline: open until filled. https://facultyjobs.ua.edu/postings/51679
Bard High School Early College Baltimore (Baltimore, MD, USA). Faculty in Spanish Language and Literature. Deadline: open until filled. https://apply.interfolio.com/100871
Concordia College (Moorhead, MN, USA). Assistant Professor of Spanish (NTT, One-Year Renewable Term). Spanish/Open specialization. Deadline April 7, 2023. https://hr.cord.edu/postings/9886
Concordia College (Moorhead, MN, USA). Assistant Professor of Spanish (NTT, Three-Year Renewable Term). Spanish/Open specialization. Deadline April 7, 2023. https://hr.cord.edu/postings/9885
Middlebury College (VT, USA). Visiting Assistant Professor of Spanish (non-tenure track, 1 year). Spanish. Deadline April 1, 2023. https://apply.interfolio.com/121976
University of Illinois at Urbana-Champaign (IL/USA). Teaching Assistant Professor and Director of Introductory Spanish (non-tenure track, 1 year renewable contract). Spanish. Deadline extended to April 10, 2023. https://illinois.csod.com/ux/ats/careersite/1/home/requisition/2283?c=illinois
University of Illinois at Urbana-Champaign (IL/USA). Lecturer/instructor and Assistant Director of Introductory Spanish (non-tenure track, 1 year renewable contract). Spanish. Deadline extended to April 10, 2023. https://illinois.csod.com/ux/ats/careersite/1/home/requisition/2282?c=illinois
Coastal Carolina University (SC). Lecturer of Spanish. https://jobs.coastal.edu/postings/19482
Loyola University Maryland (Baltimore, MD). Teaching Assistant Professor of Spanish (NTT). Application review begins March 14. https://careers.loyola.edu/postings/6644
Skidmore College (NY, USA). Visiting Assistant Professor of Spanish. Latin America. March 1, 2023. https://eodq.fa.us6.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX/job/972/?utm_medium=jobshare
University of Saint Andrews (Scotland, UK) - Lecturer (Associate Professor) of Comparative Literature. Permanent/Tenured. (Deadline: March 8th, 2023) Start: 1 August 2023 or as soon as possible thereafter. Link to Job Ad: https://www.jobs.ac.uk/job/CXF467/lecturer-in-comparative-literature-ac2344mr
Kansas State University (Manhattan KS). Teaching Assistant Professor of Spanish (3-year renewal); Generalist (PhD in Literature or Linguistics/SLA) with a background in cultural or literary studies to teach “Introduction to Hispanic Readings & Media,” a core course for undergraduate majors/minors. Deadline January 27th: https://careers.k-state.edu/en-us/job/514410/teaching-assistant-professor-of-spanish
Coastal Carolina University (Conway, SC). Lecturer in Spanish for Professional Purposes and Health Professions. Deadline January 13th - Interviews will begin early January: https://jobs.coastal.edu/postings/18845
Old Dominion University (Norfolk, VA). Lecturer in Spanish (4-4 teaching) with Second Language Acquisition or Teaching Methodolody training, to run the teacher prep program in the department of World Languages and Cultures. NTT. Permanent position. Review of applications starts December 15, 2022. https://jobs.chronicle.com/job/37363670/lecturer-of-spanish-non-tenure-track-f0918a1
University of Missouri (Columbia, MO). Assistant Professor Spanish Linguistics (TT) Second Language Acquisition, sociolinguistics, bilingualism, or classroom discourse analysis. January 15, 2023.https://joblist.mla.org/job-details/7007/assistant-professor-spanish-linguistics-tenure-track-/?porder=Spanish&so=Date&ix=12#top-pagination
Louisiana State University Shreveport (Shreveport, LA). Assistant Professor of Linguistics and/or Spanish (TT). January 20, 2023. https://joblist.mla.org/job-details/6968/assistant-professor-of-linguistics-and-or-spanish/?kw=shreveport&porder=Spanish%7cshreveport&so=Date#top-pagination
Swarthmore College, Swarthmore, PA. Postdoctoral Fellowship in Latin American and Latino Studies. The Latin American and Latino Studies Program at Swarthmore College invites applications to the Consortium for Faculty Diversity for a two-year CFD teaching post-doctoral position hosted at Swarthmore, beginning with the fall semester of 2023. We seek a colleague with a humanities or social science background who would be eager to teach an introductory course in Latin American and Latino Studies.  [...]  More information about the program can be found at https://www.swarthmore.edu/latin-american-and-latino-studies. Deadline: Dec. 20, 2022.https://careers.lasaweb.org/jobs/17810169/post-doctoral-fellowship-in-latin-american-and-latino-studies
Macalester College, St Paul, MN. Visiting Assistant Professor of Spanish. The Macalester College Department of Spanish and Portuguese invites applications for a non-tenure-track visiting position to begin Fall 2023, with possibility of renewal for up to two years. We seek a specialist in Latin American Literature and Culture of the 20th and 21st centuries, with a focus on Indigenous Studies in Mexico/Central America or the Southern Cone. Deadline 01/15/2023. https://academicjobsonline.org/ajo/jobs/23616.
Bridgewater College, Bridgewater, VA. Assistant Professor of Spanish. Preference will be given to candidates with an expertise in Peninsular Literature and Culture. Responsibilities include teaching Spanish at the introductory and intermediate levels. The teaching load is 4/3 per academic year.https://www.higheredjobs.com/details.cfm?JobCode=178184858&utm_source=11_20_22&utm_medium=email&utm_campaign=JobAgentEmail_WeeklyReview of applications starts on Dec 15, 2022.
University of Illinois, Urbana Champaign, IL. Chancellor’s Postdoctoral Research Associates. The Department of Latina/Latino Studies at the University of Illinois, Urbana-Champaign invites applications for two Chancellor’s Postdoctoral Research Associates. These are one-year appointments with a start date of August 16, 2023. Postdoctoral research associates are expected to give a presentation on their research project and to teach one of the department’s regularly offered undergraduate courses. The postdoctoral research associates will be housed in the Department of Latina/Latino Studies in the College of Liberal Arts and Sciences but will also be provided opportunities to build a supportive on-campus community with the associates from African American Studies, American Indian Studies, Asian American Studies, and Gender and Women’s Studies. https://illinois.csod.com/ux/ats/careersite/1/home/requisition/2085?c=illinois&fbclid=IwAR1Pv7fFLv19Fp3jxoImU8RK7qi6-wX_aVp6-Em3FT-NdlJ2lhiVqUYhWlU. Review of applications: Dec 12, 2022.
Adelphi University, Garden City, NY. Assistant Professor - Spanish. The Languages, Literatures and Cultures Department at Adelphi University invites qualified individuals to apply for the position of tenure-track Assistant Professor in Spanish beginning in the fall of 2023. Applicants must have native or near-native fluency in Spanish and English, experience teaching in a U.S. university setting, and Ph.D. in hand by the time of appointment. Candidates' teaching experience and research should be in Hispanic Literature. Screening of applications will begin on December 12, 2022. https://apptrkr.com/3635376
Cal Poly State University, San Luis Obispo, California. Assistant Professor of Spanish (tenure-track). Areas of specialization preferred for this position include Chicanx/Latinx Literatures and Cultures, and Spanish-English Translation/Interpretation. Additional teaching needs: Transatlantic Literary and Cultural Studies; Indigenous Literatures and Cultures of Central/Latin America. Screening of applications will begin November 7, 2022.  https://jobs.calpoly.edu/en-us/job/519285/assistant-professor-of-spanish
Miami University (Oxford, Ohio). Assistant Professor of Spanish (tenure-track). Spanish & Portuguese: Assistant Professor of Spanish (tenure-track) to teach a variety of courses, including the teaching of Spanish-language and/or culture at all levels (including graduate), maintain an active research agenda, advise students, and provide service to the department, division, and institution.  Areas of specialization and research are open. Screening of applications will begin November 8, 2022. https://jobs.miamioh.edu/cw/en-us/job/500932/assistant-professor-spanish
Oregon State University (Corvallis, OR). Assistant Professor of Spanish for Heritage Learners. The Spanish program has been in the process of re-envisioning its major and minor curriculum to include more robust and justice-oriented heritage Spanish and linguistics offerings. We seek a colleague with expertise in bilingualism/translingualism, language maintenance/attrition in the Spanish-speaking diaspora, and/or Spanish as a heritage language. This position will join the program’s efforts to center Chicanx/Latinx and Spanish Heritage speakers, advance its work in community engagement, and collaborate on wider Chicanx/Latinx initiatives in the School of Language, Culture, & Society and the university. October 31, 2022. https://jobs.oregonstate.edu/postings/127088
University of Florida (Gainesville, FL). Assistant Professor of Spanish for Specific Purposes. The Department of Spanish and Portuguese Studies at the University of Florida invites applications for the position of Assistant Professor with experience in creating, teaching, conducting research on, and coordinating Spanish for Specific Purposes courses. This is a full-time, nine-month, renewable, tenure-track position. The start date is August 16, 2023. https://explore.jobs.ufl.edu/en-us/job/524098/assistant-professor-in-spanish-for-specific-purposes?fbclid=IwAR0NpdPCt_VMFJIoJFi7aelPJLuLzZLevRWcpPAQyVJ-43jCmDukV8kO4xQ
John Jay College of Criminal Justice - CUNY (NYC, NY). Lecturer of Spanish—Specialist in Heritage Learners. December 1, 2022. https://cuny.jobs/new-york-ny/lecturer-of-spanishspecialist-in-heritage-learners/4CB89EAA5A4A429D8F722EA92CD12EDC/job/ (Translation & Interpreting also preferred!)
Louisiana Scholars' College (Natchitoches, LA). The Louisiana Scholars' College, the state's selective-admission honors college of the liberal arts and sciences, located at Northwestern State University of Louisiana, seeks applications from broadly trained individuals to fill a tenure-track position as an Assistant/ Associate Professor of Romance Languages with an anticipated start date of August 7, 2023. The ideal candidate will have a Ph.D. in hand in Romance Languages, French, Spanish, or a related field. Candidates with PhDs in French or Spanish will have significant graduate work in the other language. Fluency in a third non -English language is desirable but not required. Review of applications will begin on November 15, 2022, and will continue until the position is filled. https://agency.governmentjobs.com/louisiana/job_bulletin.cfm?JobID=3749891
University of Texas-Arlington (Arlington, TX). Assistant Professor (TT). Spanish Translation and Interpreting; Spanish for the Professions, or Spanish Localization. Secondary emphasis in Second Language Acquisition, Spanish for the Professions, such as Spanish for the Health Professions, or Spanish Localization strongly desired. Expertise in Hispanic Culture a plus. Applicants should submit a cover letter, a CV, and three letters of recommendation. November 18, 2022, and will continue until the position is filled. https://uta.peopleadmin.com/postings/20293
Oklahoma State University (Stillwater, OK). Assistant Professor (TT). Specialization in Mexican literature to begin in the Fall 2023 term. In addition to maintaining an active research agenda, this person will be expected to teach a wide range of undergraduate classes, including elementary and intermediate language as well as upper-division language, literature, and culture classes. Applicants should send a letter of application that outlines their research agenda, teaching philosophy, and diversity statement; a CV; transcripts; and three letters of recommendation by November 28, 2022.https://apply.interfolio.com/114672
University of Virginia (Charlottesville, VA). Assistant Professor (TT). 19th, 20th, or 21st-century Peninsular Spanish literature and culture. Interests and expertise in any of following fields is also desirable: Catalan, Galician, or Basque literatures and cultures; race and ethnicity; diaspora and migration; environment; theater and performance studies; women, gender, and sexuality studies; aesthetics and technology; digital humanities. Application review starts on November 14; open until filled. https://www.higheredjobs.com/faculty/details.cfm?JobCode=178141239&Title=Assistant%20Professor%2C%20Department%20of%20Spanish%2C%20Italian%20%26%20Portuguese
Tennessee Tech University (Cookeville, TN/USA). Assistant Professor (TT) or Lecturer of Spanish (renewable). Latin American Studies specialist with the ability to develop Spanish for the Professions courses (Health Services, Criminal Justice, etc.). Screening date: December 10, 2022; open until filled. https://jobs.tntech.edu/postings/14702
The Citadel (Charleston, SC / USA). Assistant Professor. Fall 2023. Spanish / French. The Department of Modern Languages, Literatures and Cultures at The Citadel, The Military College of South Carolina, invites applications for a Spanish/French Assistant Professor starting August 2023. Responsibilities include teaching all undergraduate levels of French and/or Spanish language, literature, and culture. The department offers majors and minors in both French and Spanish. The teaching load is 4-4. The possibility of faculty-led summer programs abroad after the third year and the availability of grants from The Citadel Foundation to support faculty research and presentation of research are attractive features of academic life at the college. Minimum qualifications: Candidates need a Ph.D. in hand by time of appointment. Applicants should demonstrate native or near-native fluency in French, Spanish, and English, an excellent teaching record, and show promise of scholarship. PhD in French, Spanish, or a related field with open specialization and 18 graduate hours (or an MA) in the other language. Deadline: Nov 12, 2022. https://jobs.citadel.edu/cw/en-us/job/496248/spanishfrench-assistant-professor
Iowa State University. Assistant Professor. Fall 2023. Spanish / Linguistics. The Department of World Languages & Cultures at Iowa State University in Ames, Iowa invites applications for a tenure-track Assistant Professor in Spanish to begin Fall 2023. The successful candidate will teach language and culture courses at all levels of the undergraduate curriculum and will also have interest in teaching phonology and/or translation and interpretation. The Assistant Professor will engage in the teaching and supervision of multi-section language courses of the undergraduate curriculum. The expected teaching load is four courses per academic year, but the new hire will receive a one-course release per academic year for as long as they are engaged successfully in the supervision of multi-section courses. Deadline: Nov 1, 2022. https://isu.wd1.myworkdayjobs.com/IowaStateJobs/job/Ames-IA/Assistant-Professor-of-Spanish_R9881-1
Oklahoma State University. Adjunct Instructor, Spring 2023. Oklahoma State University, Department of Languages and Literatures, is seeking applicants for a Visiting Assistant Professor of Spanish to teach four classes in the Spring 2023 semester. Master’s in Spanish or related discipline required by time of appointment, doctoral course work preferred. At least one year’s experience in college teaching preferred. Duties include teaching undergraduate courses in Spanish and participating in various departmental activities. Send letter of application, cv, transcripts, and two letters of reference by October 28, 2022 to Dr. Erik Ekman for full consideration.  Applications will continue to be reviewed until the position is filled. Apply through interfolio: https://apply.interfolio.com/114647
Florida International University (FL, USA). Assistant Professor of Spanish Linguistics. Heritage language learning and acquisition, second language acquisition, Spanish sociolinguistics, raciolinguistics, and/or linguistic anthropology. January 9th, 2023. https://joblist.mla.org/job-details/6366/assistant-professor-in-spanish-linguistics/?porder=Spanish&so=Date&ix=12#top-pagination
University of Pittsburgh (PA / USA). Assistant Professor of Latin American Literature (TT). Caribbean Studies. November 28, 2022. https://cfopitt.taleo.net/careersection/pitt_faculty_external/jobdetail.ftl?job=22007885&tz=GMT-04%3A00&tzname=America%2FNew_York
Skidmore College (NY, USA). Assistant Professor of Spanish (TT). Spanish for Specific Purposes (Business, Health Professions, etc.), Spanish for Heritage Speakers, or Translation Studies. October 31, 2022.  https://eodq.fa.us6.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX/job/842/?utm_medium=jobshare
University of Oregon (Eugene, Oregon, USA). TT Assistant Professor in Global Studies (Global Political Economy focus). Disciplinary field is open. October 15, 2022. https://careers.uoregon.edu/en-us/job/529427/assistant-professor-of-global-studies
Colorado College (CO/USA). Assistant Professor (tenure-track). Spanish/ Mexican cultures and literatures. Areas of expertise sought include, but are not limited to, Critical Indigenous Studies, U.S.-México Border Studies or Diaspora Studies. October 21, 2022. https://employment.coloradocollege.edu/postings/6389.
Tulane University (LA / USA). Research & Instruction Librarian, The Latin American Library. Develops research services, instructional programs, and engages in collection development for The Latin American Library. Candidates with Ph.D in any area of Latin American Studies and familiarity with the operations of an academic library may apply (*library degree not required*). https://apply.interfolio.com/112283
SUNY-University at Buffalo (NY / USA). Full or Advanced Associate Professor of Latin American or Hispanophone Caribbean Studies (tenured). Specialization open, but scholars with a transdisciplinary approach, who work in creoles, the African diaspora, indigenous studies, as well as those who work across more than one language of the region are particularly encouraged to apply. November 1, 2022. https://www.ubjobs.buffalo.edu/postings/37530
Fordham University (NY / USA). Associate Professor of Spanish (tenured). Foreign Language Pedagogy and/or Second Language Acquisition. November 8, 2022 (Review begins October 25, 2022). https://apply.interfolio.com/113255
DePaul University (IL / USA). Assistant Professor in Latin American and Latino Studies (TT). December 1, 2022 (Open until filled). https://academics.depaul.edu/faculty-jobs/Pages/position-detail.aspx?dpusearchbyid=465217
DePaul University (IL / USA). Assistant Professor in Spanish (TT). Mexican studies, Chicanx studies, Mexican literature and culture, or Mexican-American literature and culture. October 17, 2022. https://academics.depaul.edu/faculty-jobs/Pages/position-detail.aspx?dpusearchbyid=465218
Lehigh University (PA / USA). Assistant Professor in Spanish and Hispanic Studies (TT). November 11, 2022. https://academicjobsonline.org/ajo/jobs/22365
Boston University (MA / USA). Assistant Professor of Spanish (TT). Contemporary Latin American Literature. October 15, 2022. https://academicjobsonline.org/ajo/jobs/22399
University of Washington (WA / USA). Assistant Professor (TT) Latinx Literature and Culture. October 1, 2022. https://apply.interfolio.com/111190
Harvard University (MA / USA). Professor in Comparative Literature (TT). Two languages, with a comparative, interdisciplinary, and/or transmedia focus. November 1, 2022. https://academicpositions.harvard.edu/postings/11597
Ohio State University (OH / USA). Assistant Professor (TT) Latinx and Latin American New Media Studies. November 15, 2022 (Open until filled). https://academicjobsonline.org/ajo/jobs/22407
Ohio State University (OH / USA). Assistant/Associate Professor (TT) Bilingualism and Language Disorders in Spanish. November 1, 2022 (Open until filled). https://academicjobsonline.org/ajo/jobs/22637
Ohio State University (OH / USA). Assistant Professor (TT) Formal Syntax/Semantics in Spanish. November 1, 2022 (Open until filled). https://academicjobsonline.org/ajo/jobs/22635
University of Illinois Urbana Champain (IL USA). Assistant, Associate, Full. Latin American. Deadline: 10/12 https://illinois.csod.com/ux/ats/careersite/1/home/requisition/684?c=illinois
Institute for Research in the Humanities, University of Wisconsin-Madison (WI, USA). Fellowship, pre-1700 Europe, Spanish Iberian cultural studies and poetry. Deadline: 10/28. https://irh.wisc.edu/irh-fellowships/
Colgate University (NY / USA). Assistant Professor (TT). Colonial Latin American Literature. October 1, 2022. https://academicjobsonline.org/ajo/jobs/22394
University of Chicago (IL / USA). Assistant Professor (TT). Modern Iberian Studies or Southern Cone Studies. October 15, 2022. https://apply.interfolio.com/111360
Bryn Mawr College (PA / USA). Assistant Professor (TT). Latin American Literature and Culture, with specialization in one or more of the following areas: Afro-Latino literature and culture, ecocriticism, feminist and gender studies, immigration/migration literature, and/or indigenous studies. November 6, 2022. https://apply.interfolio.com/110367
Milligan University (TN / USA). Assistant Professor (TT). Spanish. Deadline N/A. https://www.indeed.com/viewjob?jk=36daa99de74c5396&tk=1gajcg2cvh4ep800
Institute for Research in the Humanities, University of Wisconsin-Madison (WI / USA). Fellowship (1 year, 23-24). Spanish literature of the Iberian Peninsula (esp. poetry). October 27, 2022.https://irh.wisc.edu/irh-fellowships/ (see Biruté Ciplijauskaité Fellowships at the bottom)
CUNY Baruch College (NY / USA). Assistant Professor (TT). Contemporary Latin American Literature and Culture, Mexico. December 11, 2022. https://cuny.jobs/new-york-ny/assistant-professor-in-latin-american-literature-and-culture/71D6EB0D80364DD6BFC035D1CF3A3F42/job/
Sarah Lawrence College (NY / USA). Rank not specified (TT). Spanish, African heritages across the Americas and/or transatlantic, U.S. Latinx, Indigenous, and/or LGBTQIA+ studies. October 7, 2022.https://slc.peopleadmin.com/postings/1803
Sul Ross State University (TX / USA). Open Rank (TT). Spanish, Spanish for the Professions. Deadline N/A. https://sulross.peopleadmin.com/postings/6735
Seattle University (WA / USA). Assistant Professor (TT). Spanish-Applied Linguistics, Spanish for Specific Purposes and/or Translation and Interpretation Studies. September 30, 2022.https://seattleu.csod.com/ats/careersite/JobDetails.aspx?id=1964
Loyola Marymount University (CA / USA). Assistant Professor (TT). Latin America Literary Studies and Culture. October 28, 2022. https://lmu.wd1.myworkdayjobs.com/en-US/Careers/job/Tenure-Line-Spanish_R3588
Baylor University (TX / USA). Assistant Professor (TT). Spanish, Hispanic Linguistics. October 15, 2022. https://apply.interfolio.com/108733
California State University, Dominguez Hills (CA / USA). Assistant Professor (TT). Latin American Literature. September 15, 2022. https://careers.csudh.edu/en-us/job/517505/assistant-professor-modern-languages-latin-american-literature
University of California Berkeley (CA / USA). Assistant Professor (TT). Latin American literatures and cultures with a focus on the study of migration, (im)mobility, borderlands, border crossings and the production of transnational, diasporic and border literatures, cultures and theory. September 30, 2022. https://aprecruit.berkeley.edu/JPF03558
Massachusetts Institute of Technology (MA / USA). Senior Lecturer in Spanish (5 years). Spanish. September 1, 2022. website: https://academicjobsonline.org/ajo/jobs/21836
University of Florida (FL/USA). Assistant Professor of Spanish Linguistics / Syntax. Deadline: Not specified . Link to Job ad. (Job ad has expired)
John Jay College of Criminal Justice - CUNY (NY/USA). Lecturer of Spanish—Specialist in Heritage Learners. December 1, 2022. https://cuny.jobs/new-york-ny/lecturer-of-spanishspecialist-in-heritage-learners/4CB89EAA5A4A429D8F722EA92CD12EDC/job/
Fort Hays State University (KS / USA). Instructor or Assistant Professor (NTT). Spanish. November 11, 2022 https://fhsu.wd1.myworkdayjobs.com/en-US/CAREERS/job/Spanish-Faculty-Position---Modern-Languages_R-03561
Central Connecticut State University (CT/USA). Assistant Professor of Spanish (TT). Contemporary Latin America with a preference for specialists of South America. December 15, 2022. https://www.higheredjobs.com/faculty/details.cfm?JobCode=178181343&Title=%5BC22%2D082%5D%20%20Assistant%20Professor%20of%20Spanish%20%20%28Latin%20American%20Literature%29
Central Connecticut State University (CT/USA). Assistant Professor of Spanish (TT). Peninsular Literature and Culture. December 15, 2022. https://www.higheredjobs.com/faculty/details.cfm?JobCode=178181288&Title=C22%2D081Assistant%20Professor%20of%20Spanish%20%20%28Peninsular%20Literature%29
Amherst College (MA/USA). Lecturer in Spanish (3-year appointment with possibility of renewal). Department of Spanish. January 3, 2023. https://apply.interfolio.com/118597"


